### ISSUE TITLE
I can't put GlideImage in LazyColumn

### ISSUE THREAD

**Issue by ReviewH8x** [sanjeevirajm/GlideCompose#2]
@Composable
fun Greeting(name: String, modifier: Modifier = Modifier) {
    val context = LocalContext.current
    LazyColumn (
        modifier = Modifier
            .fillMaxSize()
          //  .background(colorResource(id = R.color.lightBgColor))
            .wrapContentSize(Alignment.TopCenter)
            .padding(bottom = 50.dp),
        verticalArrangement = Arrangement.spacedBy(10.dp)

    ) {
        item {
            Column {
                GlideImage(
                    modifier = Modifier.fillMaxWidth(),
                    contentScale = ContentScale.FillWidth,
                    contentDescription = "",
                    data = "https://i.imgur.com/6IAEzpf.jpg",
                    placeHolderDrawable = AppCompatResources.getDrawable(context, R.drawable.ic_launcher_foreground)!!

                )

                Text("Hello")
            }

           
        }
    }
}

**Comment by sanjeevirajm** [comment]
Hi @ReviewH8x 
Please try having a fixed height for the image. 
Image loading works well when items inside LazyCloumn/RecyclerView have fixed height. Adding max parent might cause flickering effect, loads image with zero height, or a crash. 
Not sure what height the BoxWithConstraint will return for items inside LazyColumn.

If you can't set a fixed height because of a valid usecase, please try official glide library now.

* This library was done when Glide doesn't have any official support for compose
* Accompanist have stopped Glide support
* When other libraries have memory leak/cache issues at that time

Now Glide supports compose officially. It has full fledged compose support.
